### ISSUE TITLE
The link in the abstract of the paper "Formalising real numbers in HoTT" on arxiv does not work.

### ISSUE THREAD

**Issue by drever** [SkySkimmer/HoTTClasses#1] opened 2016-10-18 11:37 UTC
The link in the [abstract](https://arxiv.org/abs/1610.05072) links to a 404 error site. [Github had a policy change in how to link user content](https://developer.github.com/changes/2014-04-25-user-content-security/).

**Comment by SkySkimmer** [comment] 2016-10-18 11:44
Thanks for the report. The issue is unrelated to that policy change, it's happening because the end of sentence dot was added at the end of the URL.
It should be fixed whenever arXiv finishes processing the update.

**Comment by SkySkimmer** [comment] 2016-10-20 13:25
Should be fixed now.

**Closed as completed by SkySkimmer** 2016-10-20 13:25 UTC
